// eslint-disable-next-line @typescript-eslint/ban-ts-comment, @typescript-eslint/prefer-ts-expect-error
// @ts-ignore `__snaplet` could not exist yet as it's generated by `@snaplet/seed generate`
/// <reference types="__snaplet/config" />

import { type SeedConfig } from "./seedConfig.js";

export function defineConfig(config: SeedConfig) {
  return config;
}
