// eslint-disable-next-line @typescript-eslint/ban-ts-comment, @typescript-eslint/prefer-ts-expect-error
// @ts-ignore context(justinvdm, 28 February 2024): `__snaplet` is a dir generated by `npx @snaplet/seed generate`
export * from "__snaplet";
