// eslint-disable-next-line @typescript-eslint/ban-ts-comment, @typescript-eslint/prefer-ts-expect-error
// @ts-ignore `assets` could not exist yet as it's generated by `@snaplet/seed generate`
export * from "../assets/index.js";
