import { teardownRuntime } from "./runtime/teardownRuntime.js";

// @ts-expect-error context(justinvdm, 28 February 2024): `__snaplet` is a dir generated by `npx @snaplet/seed generate`
export * from "__snaplet";

process.on("beforeExit", () => {
  void teardownRuntime();
});
